{{- if .Values.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gitea.actions.fullname" . }}-act-runner-config
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "gitea.actions.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- with .Values.statefulset.actRunner.config -}}
    {{- if kindIs "string" . -}}
    {{ . | nindent 4}}
    {{- else -}}
    {{ toYaml . | nindent 4}}
    {{- end -}}
    {{- end -}}
{{- end }}
