grafana:
  service:
    type: NodePort
    nodePort: 31110 
  adminUser: "admin"
  adminPassword: "admin123"
  grafana.ini:
    security:
      disable_initial_admin_password_change: true
  additionalDataSources:
    - name: Loki
      type: loki
      uid: loki
      access: proxy
      url: http://loki-gateway.monitoring.svc.cluster.local:80
      jsonData:
        timeout: 60
        maxLines: 1000

prometheus-node-exporter:
  hostRootFsMount:
    enabled: true